backend:
  name: github
  repo: serand2048/serand2048.github.io
  branch: main
  base_url: http://localhost:3000

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Страницы (RU)"
    folder: "ru"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Содержимое", name: "body", widget: "markdown" }

  - name: "pages_en"
    label: "Pages (EN)"
    folder: "en"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }