backend:
  name: github
  repo: serand2048/serand2048.github.io
  branch: main
  base_url: http://localhost:3000

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Страницы"
    folder: "ru"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Содержимое", name: "body", widget: "markdown" }